### PR TITLE
Fix body height

### PR DESCRIPTION
**Pull request by AI-Mozi**
This changes fix display for the bodies with no elements like `queue`.

Before
Screenshot 2024-04-23 at 21 02 40
After
Screenshot 2024-04-23 at 21 03 52

### CODE REVIEW

**Comment by postmodern** [comment]
I think `min-height` should use `100vh` or something more relative to the screen's height. On my display (2560x1440) I get this:
localhost_1337_queue

**Review by postmodern — CHANGES_REQUESTED** [review]
Still displaying weird on my screen (2560x1440).

**Comment by AI-Mozi** [comment]
`min-width: 75vh` should looks ok, could you check it on your display?

**Comment by postmodern** [comment]
@AI-Mozi `75vh` and `70vh` pushes the footer just below the bottom of the window, which I think is the goal?

**Comment by postmodern** [comment]
@AI-Mozi do we want the footer to be at the bottom of the page and visible, if there's no page content, or should it always be below the first page and require scrolling down to view it?

**Review by postmodern — APPROVED** [review]

**Comment by postmodern** [comment]
Changed `min-height` to `70vh` and squash merged.

**Pull request merged**
